In [ ]:
https://vega.github.io/vega-datasets/

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from vega_datasets import data as vds
pd.set_option('display.max_rows', 1000)

In [3]:
url = "https://en.wikipedia.org/wiki/Demographics_of_the_world"
population = pd.read_html(url)[4]
population.head()

,Rank,City,Population,Country,Statistical concept[28],Area (km²)[a],Density (p/km²)
0,1,Tokyo,30000000,Japan,Metropolitan area[b],13500,2716
1,2,Shanghai,24180000,China,Urban agglomeration[c],3920,6168
2,3,Mexico City,22460000,Mexico,Metropolitan area (zona metropolitana),7815,2490
3,4,Delhi,22157000,India,Urban agglomeration[d],33578,659
4,5,Lagos,21000000,Nigeria,Metropolitan area (região metropolitana),10050,3400

In [4]:
url = 'https://en.wikipedia.org/wiki/List_of_cities_and_towns_in_Russia_by_population'
Russia_by_population = pd.read_html(url)[0]
Russia_by_population.head()

  Rank         City/town          Russian                     Federal subject  \
  Rank         City/town          Russian                     Federal subject
0    1            Moscow           Москва            Moscow (federal city)[4]
1    2  Saint Petersburg  Санкт-Петербург  Saint Petersburg (federal city)[5]
2    3       Novosibirsk      Новосибирск                  Novosibirsk Oblast
3    4     Yekaterinburg     Екатеринбург                   Sverdlovsk Oblast
4    5   Nizhny Novgorod  Нижний Новгород              Nizhny Novgorod Oblast

  Federal district                            Population                   \
  Federal district 2019 estimate (1-167)[1] (168-317)[2] (2010 Census)[3]
0          Central                              12432531         11503501
1        Northwest                               5383890          4879566
2          Siberia                               1618039          1473754
3             Ural                               1483119          1349772
4            Volga                               1253511          1250619

    Change
    Change
0   +8.08%
1  +10.34%
2   +9.79%
3   +9.88%
4   +0.23%

In [5]:
url = 'https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population'
cities_pop = pd.read_html(url)[4]
cities_pop.head()

,2019rank,City,State[c],2019estimate,2010Census,Change,2016 land area,2016 land area.1,2016 population density,2016 population density.1,Location
0,1,New York[d],New York,8336817,8175133,+1.98%,301.5 sq mi,780.9 km2,"28,317/sq mi","10,933/km2",40°39′49″N 73°56′19″W﻿ / ﻿40.6635°N 73.9387°W
1,2,Los Angeles,California,3979576,3792621,+4.93%,468.7 sq mi,"1,213.9 km2","8,484/sq mi","3,276/km2",34°01′10″N 118°24′39″W﻿ / ﻿34.0194°N 118.4108°W
2,3,Chicago,Illinois,2693976,2695598,−0.06%,227.3 sq mi,588.7 km2,"11,900/sq mi","4,600/km2",41°50′15″N 87°40′54″W﻿ / ﻿41.8376°N 87.6818°W
3,4,Houston[3],Texas,2320268,2100263,+10.48%,637.5 sq mi,"1,651.1 km2","3,613/sq mi","1,395/km2",29°47′12″N 95°23′27″W﻿ / ﻿29.7866°N 95.3909°W
4,5,Phoenix,Arizona,1680992,1445632,+16.28%,517.6 sq mi,"1,340.6 km2","3,120/sq mi","1,200/km2",33°34′20″N 112°05′24″W﻿ / ﻿33.5722°N 112.0901°W

In [11]:
url = 'https://www.britannica.com/topic/list-of-the-populations-of-the-worlds-countries-dependencies-and-territories-2156538'
COVID = pd.read_html(url)[0]
COVID.head()

  country, dependency, or territory              population population rank
0                       Afghanistan  (2019 est.) 33,110,000       (2018) 45
1                           Albania   (2019 est.) 2,861,000      (2018) 139
2                           Algeria  (2019 est.) 43,583,000       (2018) 34
3                    American Samoa      (2019 est.) 60,500      (2018) 210
4                           Andorra      (2019 est.) 76,900      (2018) 205